  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Talks"
  weight = 200
  identifier = "posts"
  url = "/talks"

  [[main]]
  name = "Slides"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "Publications"
  weight = 500
  identifier = "publications"
  url = "/publications"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"